name: Publish Website to CSORS
on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        passive: true          # Enable passive mode for better connection handling
        transfer-strategy: basic  # Use a basic transfer strategy
        timeout: 600           # Set a longer timeout (600 seconds)
